name: Integration Test

on:
  push:
  pull_request:
    types: [opened]

jobs:
  test_notifications:
    runs-on: [ubuntu-latest]
    services:
      slack_mock:
        image: alpine:latest
        ports:
          - 8085:8085
    steps:
      - name: Test
        run: ping slack_mock -c 1